// examples/vercel-ai-chat/src/components/chat-header.tsx
import { Sparkles } from "lucide-react";
import { SidebarToggle } from "./sidebar-toggle";

interface ChatHeaderProps {
  isSidebarOpen: boolean;
  onToggleSidebar: () => void;
}

export function ChatHeader({ isSidebarOpen, onToggleSidebar }: ChatHeaderProps) {
  return (
    <header className="shrink-0 border-b border-zinc-200 dark:border-zinc-800 px-4 py-3">
      <div className="flex items-center gap-2">
        <SidebarToggle isOpen={isSidebarOpen} onToggle={onToggleSidebar} />
        <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-violet-500 to-indigo-600 flex items-center justify-center">
          <Sparkles size={14} className="text-white" />
        </div>
        <div className="flex flex-col items-start">
        <h1 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Vercel AI Chat</h1>
        <span className="text-xs text-zinc-400 dark:text-zinc-500">
          Vercel AI SDK + 感知未来 Renderer
        </span>
        </div>
      </div>
    </header>
  );
}

// examples/svelte-chat/src/routes/ChatHeader.svelte
<script lang="ts">
</script>

<header
	class="shrink-0 border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 px-6 py-4"
>
	<h1 class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">感知未来 Svelte Chat</h1>
	<p class="text-xs text-zinc-500 dark:text-zinc-400">
		Powered by @openuidev/svelte-lang & Vercel AI SDK
	</p>
</header>
